//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 *  Copyright (c) 2022 NetApp
 *  All rights reserved
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResource) DeepCopyInto(out *ContainerResource) {
	*out = *in
	out.MemRequest = in.MemRequest.DeepCopy()
	out.CPUsRequest = in.CPUsRequest.DeepCopy()
	out.MemLimit = in.MemLimit.DeepCopy()
	out.CPUsLimit = in.CPUsLimit.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResource.
func (in *ContainerResource) DeepCopy() *ContainerResource {
	if in == nil {
		return nil
	}
	out := new(ContainerResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfig) DeepCopyInto(out *ControllerConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfig.
func (in *ControllerConfig) DeepCopy() *ControllerConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronSchedule) DeepCopyInto(out *CronSchedule) {
	*out = *in
	if in.Months != nil {
		in, out := &in.Months, &out.Months
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.DaysOfMonth != nil {
		in, out := &in.DaysOfMonth, &out.DaysOfMonth
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.DaysOfWeek != nil {
		in, out := &in.DaysOfWeek, &out.DaysOfWeek
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Hours != nil {
		in, out := &in.Hours, &out.Hours
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Minutes != nil {
		in, out := &in.Minutes, &out.Minutes
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronSchedule.
func (in *CronSchedule) DeepCopy() *CronSchedule {
	if in == nil {
		return nil
	}
	out := new(CronSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportRule) DeepCopyInto(out *ExportRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportRule.
func (in *ExportRule) DeepCopy() *ExportRule {
	if in == nil {
		return nil
	}
	out := new(ExportRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ILB) DeepCopyInto(out *ILB) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ILB.
func (in *ILB) DeepCopy() *ILB {
	if in == nil {
		return nil
	}
	out := new(ILB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Images) DeepCopyInto(out *Images) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Images.
func (in *Images) DeepCopy() *Images {
	if in == nil {
		return nil
	}
	out := new(Images)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Logging) DeepCopyInto(out *Logging) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging.
func (in *Logging) DeepCopy() *Logging {
	if in == nil {
		return nil
	}
	out := new(Logging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppClusterPeering) DeepCopyInto(out *NetAppClusterPeering) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppClusterPeering.
func (in *NetAppClusterPeering) DeepCopy() *NetAppClusterPeering {
	if in == nil {
		return nil
	}
	out := new(NetAppClusterPeering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppClusterPeering) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppClusterPeeringCondition) DeepCopyInto(out *NetAppClusterPeeringCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppClusterPeeringCondition.
func (in *NetAppClusterPeeringCondition) DeepCopy() *NetAppClusterPeeringCondition {
	if in == nil {
		return nil
	}
	out := new(NetAppClusterPeeringCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppClusterPeeringList) DeepCopyInto(out *NetAppClusterPeeringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetAppClusterPeering, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppClusterPeeringList.
func (in *NetAppClusterPeeringList) DeepCopy() *NetAppClusterPeeringList {
	if in == nil {
		return nil
	}
	out := new(NetAppClusterPeeringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppClusterPeeringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppClusterPeeringSpec) DeepCopyInto(out *NetAppClusterPeeringSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppClusterPeeringSpec.
func (in *NetAppClusterPeeringSpec) DeepCopy() *NetAppClusterPeeringSpec {
	if in == nil {
		return nil
	}
	out := new(NetAppClusterPeeringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppClusterPeeringStatus) DeepCopyInto(out *NetAppClusterPeeringStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NetAppClusterPeeringCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppClusterPeeringStatus.
func (in *NetAppClusterPeeringStatus) DeepCopy() *NetAppClusterPeeringStatus {
	if in == nil {
		return nil
	}
	out := new(NetAppClusterPeeringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppExportPolicy) DeepCopyInto(out *NetAppExportPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppExportPolicy.
func (in *NetAppExportPolicy) DeepCopy() *NetAppExportPolicy {
	if in == nil {
		return nil
	}
	out := new(NetAppExportPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppExportPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppExportPolicyList) DeepCopyInto(out *NetAppExportPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetAppExportPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppExportPolicyList.
func (in *NetAppExportPolicyList) DeepCopy() *NetAppExportPolicyList {
	if in == nil {
		return nil
	}
	out := new(NetAppExportPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppExportPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppExportPolicySpec) DeepCopyInto(out *NetAppExportPolicySpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ExportRule, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppExportPolicySpec.
func (in *NetAppExportPolicySpec) DeepCopy() *NetAppExportPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetAppExportPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppExportPolicyStatus) DeepCopyInto(out *NetAppExportPolicyStatus) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ExportRule, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppExportPolicyStatus.
func (in *NetAppExportPolicyStatus) DeepCopy() *NetAppExportPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NetAppExportPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppServiceLevel) DeepCopyInto(out *NetAppServiceLevel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppServiceLevel.
func (in *NetAppServiceLevel) DeepCopy() *NetAppServiceLevel {
	if in == nil {
		return nil
	}
	out := new(NetAppServiceLevel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppServiceLevel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppServiceLevelList) DeepCopyInto(out *NetAppServiceLevelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetAppServiceLevel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppServiceLevelList.
func (in *NetAppServiceLevelList) DeepCopy() *NetAppServiceLevelList {
	if in == nil {
		return nil
	}
	out := new(NetAppServiceLevelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppServiceLevelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppServiceLevelSpec) DeepCopyInto(out *NetAppServiceLevelSpec) {
	*out = *in
	out.CapacityLimit = in.CapacityLimit.DeepCopy()
	if in.QuarkPodBuckets != nil {
		in, out := &in.QuarkPodBuckets, &out.QuarkPodBuckets
		*out = make([]QuarkPodBucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppServiceLevelSpec.
func (in *NetAppServiceLevelSpec) DeepCopy() *NetAppServiceLevelSpec {
	if in == nil {
		return nil
	}
	out := new(NetAppServiceLevelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppServiceLevelStatus) DeepCopyInto(out *NetAppServiceLevelStatus) {
	*out = *in
	if in.QuarkPodBuckets != nil {
		in, out := &in.QuarkPodBuckets, &out.QuarkPodBuckets
		*out = make([]QuarkPodBucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppServiceLevelStatus.
func (in *NetAppServiceLevelStatus) DeepCopy() *NetAppServiceLevelStatus {
	if in == nil {
		return nil
	}
	out := new(NetAppServiceLevelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppSnapshotPolicy) DeepCopyInto(out *NetAppSnapshotPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppSnapshotPolicy.
func (in *NetAppSnapshotPolicy) DeepCopy() *NetAppSnapshotPolicy {
	if in == nil {
		return nil
	}
	out := new(NetAppSnapshotPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppSnapshotPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppSnapshotPolicyList) DeepCopyInto(out *NetAppSnapshotPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetAppSnapshotPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppSnapshotPolicyList.
func (in *NetAppSnapshotPolicyList) DeepCopy() *NetAppSnapshotPolicyList {
	if in == nil {
		return nil
	}
	out := new(NetAppSnapshotPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppSnapshotPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppSnapshotPolicySpec) DeepCopyInto(out *NetAppSnapshotPolicySpec) {
	*out = *in
	if in.Schedules != nil {
		in, out := &in.Schedules, &out.Schedules
		*out = make([]CronSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppSnapshotPolicySpec.
func (in *NetAppSnapshotPolicySpec) DeepCopy() *NetAppSnapshotPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetAppSnapshotPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppSnapshotPolicyStatus) DeepCopyInto(out *NetAppSnapshotPolicyStatus) {
	*out = *in
	if in.Schedules != nil {
		in, out := &in.Schedules, &out.Schedules
		*out = make([]CronSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppSnapshotPolicyStatus.
func (in *NetAppSnapshotPolicyStatus) DeepCopy() *NetAppSnapshotPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NetAppSnapshotPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppStoragePool) DeepCopyInto(out *NetAppStoragePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppStoragePool.
func (in *NetAppStoragePool) DeepCopy() *NetAppStoragePool {
	if in == nil {
		return nil
	}
	out := new(NetAppStoragePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppStoragePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppStoragePoolCondition) DeepCopyInto(out *NetAppStoragePoolCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.FirstStoragePoolOnlineTime.DeepCopyInto(&out.FirstStoragePoolOnlineTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppStoragePoolCondition.
func (in *NetAppStoragePoolCondition) DeepCopy() *NetAppStoragePoolCondition {
	if in == nil {
		return nil
	}
	out := new(NetAppStoragePoolCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppStoragePoolList) DeepCopyInto(out *NetAppStoragePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetAppStoragePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppStoragePoolList.
func (in *NetAppStoragePoolList) DeepCopy() *NetAppStoragePoolList {
	if in == nil {
		return nil
	}
	out := new(NetAppStoragePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppStoragePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppStoragePoolSpec) DeepCopyInto(out *NetAppStoragePoolSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	out.ProvisionedSize = in.ProvisionedSize.DeepCopy()
	if in.ADDNSIPs != nil {
		in, out := &in.ADDNSIPs, &out.ADDNSIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.SMBServerConfiguration = in.SMBServerConfiguration
	out.SMBADConfiguration = in.SMBADConfiguration
	if in.AvailableZones != nil {
		in, out := &in.AvailableZones, &out.AvailableZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastZoneMigrationTime != nil {
		in, out := &in.LastZoneMigrationTime, &out.LastZoneMigrationTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppStoragePoolSpec.
func (in *NetAppStoragePoolSpec) DeepCopy() *NetAppStoragePoolSpec {
	if in == nil {
		return nil
	}
	out := new(NetAppStoragePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppStoragePoolStatus) DeepCopyInto(out *NetAppStoragePoolStatus) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	out.ProvisionedSize = in.ProvisionedSize.DeepCopy()
	if in.ADDNSIPs != nil {
		in, out := &in.ADDNSIPs, &out.ADDNSIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.SMBServerConfiguration = in.SMBServerConfiguration
	out.SMBADConfiguration = in.SMBADConfiguration
	if in.DataPvcs != nil {
		in, out := &in.DataPvcs, &out.DataPvcs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AvailableZones != nil {
		in, out := &in.AvailableZones, &out.AvailableZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastZoneMigrationTime != nil {
		in, out := &in.LastZoneMigrationTime, &out.LastZoneMigrationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NetAppStoragePoolCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppStoragePoolStatus.
func (in *NetAppStoragePoolStatus) DeepCopy() *NetAppStoragePoolStatus {
	if in == nil {
		return nil
	}
	out := new(NetAppStoragePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolume) DeepCopyInto(out *NetAppVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolume.
func (in *NetAppVolume) DeepCopy() *NetAppVolume {
	if in == nil {
		return nil
	}
	out := new(NetAppVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeCloudSnapshot) DeepCopyInto(out *NetAppVolumeCloudSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeCloudSnapshot.
func (in *NetAppVolumeCloudSnapshot) DeepCopy() *NetAppVolumeCloudSnapshot {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeCloudSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolumeCloudSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeCloudSnapshotCondition) DeepCopyInto(out *NetAppVolumeCloudSnapshotCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeCloudSnapshotCondition.
func (in *NetAppVolumeCloudSnapshotCondition) DeepCopy() *NetAppVolumeCloudSnapshotCondition {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeCloudSnapshotCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeCloudSnapshotList) DeepCopyInto(out *NetAppVolumeCloudSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetAppVolumeCloudSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeCloudSnapshotList.
func (in *NetAppVolumeCloudSnapshotList) DeepCopy() *NetAppVolumeCloudSnapshotList {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeCloudSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolumeCloudSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeCloudSnapshotSpec) DeepCopyInto(out *NetAppVolumeCloudSnapshotSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeCloudSnapshotSpec.
func (in *NetAppVolumeCloudSnapshotSpec) DeepCopy() *NetAppVolumeCloudSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeCloudSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeCloudSnapshotStatus) DeepCopyInto(out *NetAppVolumeCloudSnapshotStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NetAppVolumeCloudSnapshotCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CreationTime.DeepCopyInto(&out.CreationTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeCloudSnapshotStatus.
func (in *NetAppVolumeCloudSnapshotStatus) DeepCopy() *NetAppVolumeCloudSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeCloudSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeCondition) DeepCopyInto(out *NetAppVolumeCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.FirstVolumeOnlineTime.DeepCopyInto(&out.FirstVolumeOnlineTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeCondition.
func (in *NetAppVolumeCondition) DeepCopy() *NetAppVolumeCondition {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeList) DeepCopyInto(out *NetAppVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetAppVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeList.
func (in *NetAppVolumeList) DeepCopy() *NetAppVolumeList {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeReplication) DeepCopyInto(out *NetAppVolumeReplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeReplication.
func (in *NetAppVolumeReplication) DeepCopy() *NetAppVolumeReplication {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeReplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolumeReplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeReplicationCondition) DeepCopyInto(out *NetAppVolumeReplicationCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeReplicationCondition.
func (in *NetAppVolumeReplicationCondition) DeepCopy() *NetAppVolumeReplicationCondition {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeReplicationCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeReplicationList) DeepCopyInto(out *NetAppVolumeReplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetAppVolumeReplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeReplicationList.
func (in *NetAppVolumeReplicationList) DeepCopy() *NetAppVolumeReplicationList {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeReplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolumeReplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeReplicationSpec) DeepCopyInto(out *NetAppVolumeReplicationSpec) {
	*out = *in
	out.DestinationVolume = in.DestinationVolume
	out.SourceVolume = in.SourceVolume
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeReplicationSpec.
func (in *NetAppVolumeReplicationSpec) DeepCopy() *NetAppVolumeReplicationSpec {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeReplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeReplicationStatus) DeepCopyInto(out *NetAppVolumeReplicationStatus) {
	*out = *in
	in.NewestSnapshotTime.DeepCopyInto(&out.NewestSnapshotTime)
	in.LastTransferEndTime.DeepCopyInto(&out.LastTransferEndTime)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NetAppVolumeReplicationCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeReplicationStatus.
func (in *NetAppVolumeReplicationStatus) DeepCopy() *NetAppVolumeReplicationStatus {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeReplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeReplicationVolume) DeepCopyInto(out *NetAppVolumeReplicationVolume) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeReplicationVolume.
func (in *NetAppVolumeReplicationVolume) DeepCopy() *NetAppVolumeReplicationVolume {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeReplicationVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSnapshot) DeepCopyInto(out *NetAppVolumeSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSnapshot.
func (in *NetAppVolumeSnapshot) DeepCopy() *NetAppVolumeSnapshot {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolumeSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSnapshotCondition) DeepCopyInto(out *NetAppVolumeSnapshotCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSnapshotCondition.
func (in *NetAppVolumeSnapshotCondition) DeepCopy() *NetAppVolumeSnapshotCondition {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSnapshotCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSnapshotInfo) DeepCopyInto(out *NetAppVolumeSnapshotInfo) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	in.CreationTime.DeepCopyInto(&out.CreationTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSnapshotInfo.
func (in *NetAppVolumeSnapshotInfo) DeepCopy() *NetAppVolumeSnapshotInfo {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSnapshotInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSnapshotList) DeepCopyInto(out *NetAppVolumeSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetAppVolumeSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSnapshotList.
func (in *NetAppVolumeSnapshotList) DeepCopy() *NetAppVolumeSnapshotList {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolumeSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSnapshotSpec) DeepCopyInto(out *NetAppVolumeSnapshotSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSnapshotSpec.
func (in *NetAppVolumeSnapshotSpec) DeepCopy() *NetAppVolumeSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSnapshotStatus) DeepCopyInto(out *NetAppVolumeSnapshotStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NetAppVolumeSnapshotCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSnapshotStatus.
func (in *NetAppVolumeSnapshotStatus) DeepCopy() *NetAppVolumeSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSnapshotsList) DeepCopyInto(out *NetAppVolumeSnapshotsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSnapshotsList.
func (in *NetAppVolumeSnapshotsList) DeepCopy() *NetAppVolumeSnapshotsList {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSnapshotsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolumeSnapshotsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSnapshotsListCondition) DeepCopyInto(out *NetAppVolumeSnapshotsListCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSnapshotsListCondition.
func (in *NetAppVolumeSnapshotsListCondition) DeepCopy() *NetAppVolumeSnapshotsListCondition {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSnapshotsListCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSnapshotsListList) DeepCopyInto(out *NetAppVolumeSnapshotsListList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetAppVolumeSnapshotsList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSnapshotsListList.
func (in *NetAppVolumeSnapshotsListList) DeepCopy() *NetAppVolumeSnapshotsListList {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSnapshotsListList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolumeSnapshotsListList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSnapshotsListSpec) DeepCopyInto(out *NetAppVolumeSnapshotsListSpec) {
	*out = *in
	if in.DeletedSnapshots != nil {
		in, out := &in.DeletedSnapshots, &out.DeletedSnapshots
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSnapshotsListSpec.
func (in *NetAppVolumeSnapshotsListSpec) DeepCopy() *NetAppVolumeSnapshotsListSpec {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSnapshotsListSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSnapshotsListStatus) DeepCopyInto(out *NetAppVolumeSnapshotsListStatus) {
	*out = *in
	if in.DeletedSnapshots != nil {
		in, out := &in.DeletedSnapshots, &out.DeletedSnapshots
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Snapshots != nil {
		in, out := &in.Snapshots, &out.Snapshots
		*out = make([]NetAppVolumeSnapshotInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NetAppVolumeSnapshotsListCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSnapshotsListStatus.
func (in *NetAppVolumeSnapshotsListStatus) DeepCopy() *NetAppVolumeSnapshotsListStatus {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSnapshotsListStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeSpec) DeepCopyInto(out *NetAppVolumeSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	out.RestoreCacheSize = in.RestoreCacheSize.DeepCopy()
	in.SMBConfiguration.DeepCopyInto(&out.SMBConfiguration)
	out.ProvisionedSize = in.ProvisionedSize.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeSpec.
func (in *NetAppVolumeSpec) DeepCopy() *NetAppVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeStatus) DeepCopyInto(out *NetAppVolumeStatus) {
	*out = *in
	in.SMBConfiguration.DeepCopyInto(&out.SMBConfiguration)
	if in.DataPvcs != nil {
		in, out := &in.DataPvcs, &out.DataPvcs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Size = in.Size.DeepCopy()
	out.RestoreCacheSize = in.RestoreCacheSize.DeepCopy()
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NetAppVolumeCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ProvisionedSize = in.ProvisionedSize.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeStatus.
func (in *NetAppVolumeStatus) DeepCopy() *NetAppVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeUsage) DeepCopyInto(out *NetAppVolumeUsage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeUsage.
func (in *NetAppVolumeUsage) DeepCopy() *NetAppVolumeUsage {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolumeUsage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeUsageList) DeepCopyInto(out *NetAppVolumeUsageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetAppVolumeUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeUsageList.
func (in *NetAppVolumeUsageList) DeepCopy() *NetAppVolumeUsageList {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeUsageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetAppVolumeUsageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeUsageSpec) DeepCopyInto(out *NetAppVolumeUsageSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeUsageSpec.
func (in *NetAppVolumeUsageSpec) DeepCopy() *NetAppVolumeUsageSpec {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeUsageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAppVolumeUsageStatus) DeepCopyInto(out *NetAppVolumeUsageStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAppVolumeUsageStatus.
func (in *NetAppVolumeUsageStatus) DeepCopy() *NetAppVolumeUsageStatus {
	if in == nil {
		return nil
	}
	out := new(NetAppVolumeUsageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodevolImages) DeepCopyInto(out *NodevolImages) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodevolImages.
func (in *NodevolImages) DeepCopy() *NodevolImages {
	if in == nil {
		return nil
	}
	out := new(NodevolImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodevolSet) DeepCopyInto(out *NodevolSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodevolSet.
func (in *NodevolSet) DeepCopy() *NodevolSet {
	if in == nil {
		return nil
	}
	out := new(NodevolSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodevolSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodevolSetList) DeepCopyInto(out *NodevolSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodevolSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodevolSetList.
func (in *NodevolSetList) DeepCopy() *NodevolSetList {
	if in == nil {
		return nil
	}
	out := new(NodevolSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodevolSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodevolSetSpec) DeepCopyInto(out *NodevolSetSpec) {
	*out = *in
	out.Volume = in.Volume
	out.Images = in.Images
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodevolSetSpec.
func (in *NodevolSetSpec) DeepCopy() *NodevolSetSpec {
	if in == nil {
		return nil
	}
	out := new(NodevolSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodevolSetStatus) DeepCopyInto(out *NodevolSetStatus) {
	*out = *in
	in.LastUpdatedTime.DeepCopyInto(&out.LastUpdatedTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodevolSetStatus.
func (in *NodevolSetStatus) DeepCopy() *NodevolSetStatus {
	if in == nil {
		return nil
	}
	out := new(NodevolSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodevolVolume) DeepCopyInto(out *NodevolVolume) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodevolVolume.
func (in *NodevolVolume) DeepCopy() *NodevolVolume {
	if in == nil {
		return nil
	}
	out := new(NodevolVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Quark) DeepCopyInto(out *Quark) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Quark.
func (in *Quark) DeepCopy() *Quark {
	if in == nil {
		return nil
	}
	out := new(Quark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Quark) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuarkHealth) DeepCopyInto(out *QuarkHealth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuarkHealth.
func (in *QuarkHealth) DeepCopy() *QuarkHealth {
	if in == nil {
		return nil
	}
	out := new(QuarkHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuarkList) DeepCopyInto(out *QuarkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Quark, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuarkList.
func (in *QuarkList) DeepCopy() *QuarkList {
	if in == nil {
		return nil
	}
	out := new(QuarkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuarkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuarkPodBucket) DeepCopyInto(out *QuarkPodBucket) {
	*out = *in
	out.NvramSize = in.NvramSize.DeepCopy()
	out.MinVolumeSize = in.MinVolumeSize.DeepCopy()
	out.MaxVolumeSize = in.MaxVolumeSize.DeepCopy()
	out.DmsCPUs = in.DmsCPUs.DeepCopy()
	if in.ContainerResources != nil {
		in, out := &in.ContainerResources, &out.ContainerResources
		*out = make([]ContainerResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuarkPodBucket.
func (in *QuarkPodBucket) DeepCopy() *QuarkPodBucket {
	if in == nil {
		return nil
	}
	out := new(QuarkPodBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuarkSpec) DeepCopyInto(out *QuarkSpec) {
	*out = *in
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]Secret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.StorageClass.DeepCopyInto(&out.StorageClass)
	if in.ServiceLevels != nil {
		in, out := &in.ServiceLevels, &out.ServiceLevels
		*out = make([]ServiceLevel, len(*in))
		copy(*out, *in)
	}
	out.Volume = in.Volume
	out.ILB = in.ILB
	out.Images = in.Images
	out.Project = in.Project
	out.Logging = in.Logging
	out.ControllerConfig = in.ControllerConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuarkSpec.
func (in *QuarkSpec) DeepCopy() *QuarkSpec {
	if in == nil {
		return nil
	}
	out := new(QuarkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuarkStatus) DeepCopyInto(out *QuarkStatus) {
	*out = *in
	out.Images = in.Images
	out.Health = in.Health
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuarkStatus.
func (in *QuarkStatus) DeepCopy() *QuarkStatus {
	if in == nil {
		return nil
	}
	out := new(QuarkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCProvisioner) DeepCopyInto(out *SCProvisioner) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCProvisioner.
func (in *SCProvisioner) DeepCopy() *SCProvisioner {
	if in == nil {
		return nil
	}
	out := new(SCProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMBADConfiguration) DeepCopyInto(out *SMBADConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMBADConfiguration.
func (in *SMBADConfiguration) DeepCopy() *SMBADConfiguration {
	if in == nil {
		return nil
	}
	out := new(SMBADConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMBConfiguration) DeepCopyInto(out *SMBConfiguration) {
	*out = *in
	if in.DNSIPs != nil {
		in, out := &in.DNSIPs, &out.DNSIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMBConfiguration.
func (in *SMBConfiguration) DeepCopy() *SMBConfiguration {
	if in == nil {
		return nil
	}
	out := new(SMBConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMBServerConfiguration) DeepCopyInto(out *SMBServerConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMBServerConfiguration.
func (in *SMBServerConfiguration) DeepCopy() *SMBServerConfiguration {
	if in == nil {
		return nil
	}
	out := new(SMBServerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Secret) DeepCopyInto(out *Secret) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Secret.
func (in *Secret) DeepCopy() *Secret {
	if in == nil {
		return nil
	}
	out := new(Secret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLevel) DeepCopyInto(out *ServiceLevel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLevel.
func (in *ServiceLevel) DeepCopy() *ServiceLevel {
	if in == nil {
		return nil
	}
	out := new(ServiceLevel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClass) DeepCopyInto(out *StorageClass) {
	*out = *in
	if in.Provisioners != nil {
		in, out := &in.Provisioners, &out.Provisioners
		*out = make([]SCProvisioner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClass.
func (in *StorageClass) DeepCopy() *StorageClass {
	if in == nil {
		return nil
	}
	out := new(StorageClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Volume) DeepCopyInto(out *Volume) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Volume.
func (in *Volume) DeepCopy() *Volume {
	if in == nil {
		return nil
	}
	out := new(Volume)
	in.DeepCopyInto(out)
	return out
}
